version: '3'
services:
  note-app:
    image: im594/mininote-md:latest
    ports:
      - "3456:3456"
    volumes:
      - ./data:/app/data
    environment:
      - PASSWORD=your-secure-password
      - SALT=your-secure-salt
      - NODE_ENV=production
    restart: unless-stopped